### ISSUE TITLE
Full working example

### ISSUE THREAD

**Issue by renato2099** [CakePHP-Copula/Twitter#1]
Hey man, your code rocks, but I am afraid I am not being able to use it. I am a newbie using CakePhp and tried to use your plugin but I think I am missing lots of classes before actually using it.
I pulled the Apis Plugin but then I dunno how to join it with the Twitter one. I also got confused with the folder structure, could you help me out please? Maybe providing a full working example of your plugins? Thanks a ton

Renato M.

**Comment by ProLoser** [comment]
Sorry for the super late response. Work. Other crap.

Anywho, the thing is only coded to create tweets at the moment, need to add the other paths to the config file, but that's easy to do if you want.

Follow these instructions for installation on Cake2: https://github.com/ProLoser/CakePHP-LinkedIn

**Comment by ProLoser** [comment]
A super basic copy-paste of my current (and only) implementation at this time:

```
public function afterSave($created) {
    if ($created) {
        // Auto Tweet Bookmarks
        $this->setDataSource('twitter');
        $data = array(
            'section' => 'tweets',
            'status' => $this->data['Bookmark']['name'] . ' ' . $this->data['Bookmark']['url']
        );
        $this->create();
        $this->save($data);
        $this->setDataSource('default');
    }
}
```

**Comment by ozezyweb** [comment]
I feel like i'm missing something, I just want to be able to send tweets but, i'm just not understanding how. Maybe i'm just tired

**Comment by ProLoser** [comment]
@ozezyweb you're going to have to give me more information than that if you actually expect me to help you. Try pasting some code.

**Comment by ozezyweb** [comment]
Wow that was quick. I don't have any code to paste yet, I just want to know how to send a tweet manually form a controller action

**Comment by ProLoser** [comment]
The code in the README should do the trick. You need to add a database
configuration to access the Twitter API, then you switch to the Twitter
datasource and execute a save as if you were simply saving a record to the
DB. It is designed to behave nearly identically to methods you're already
used to.

On Sat, Aug 25, 2012 at 6:55 PM, Bobby notifications@github.com wrote:

> Wow that was quick. I don't have any code to paste yet, I just want to
> know how to send a tweet manually form a controller action
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ProLoser/CakePHP-Twitter/issues/1#issuecomment-8029375.

## 

Dean J Sofer
DeanSofer@gmail.com

BS Computer Information Systems
California State Polytechnic University, Pomona
Telephone: 714-900-2254
Website: www.DeanSofer.com
Github: github.com/ProLoser
